# Messages for Calculator Program
---
:welcome: "Welcome to Calculator! Enter your name:"
:need_valid_name: "Make sure to use a valid name."
:greeting: "Hello, %{name}!"
:first_num: "What's the first number?"
:invalid_num: "Hmm... that doesn't look like a valid number."
:second_num: "What's the second number?"
:choose_operation: | 
  What operation would you like to perform?
    1) add
    2) subtract
    3) multiply
    4) divide
:invalid_operator: "Must choose 1, 2, 3, or 4"
:display_operation: "%{op_name_as_verb} the two numbers..."
:adding: "Adding"
:subtracting: "Subtracting"
:multiplying: "Multiplying"
:dividing: "Dividing"
:result: "The result is %{answer}"
:again?: "Do you want to perform another calculation? (Y to calculate again)"
:goodbye: "Thank you for using the calculator. Goodbye!"
